// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oigsvlpwzlcyocjgexna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZ3N2bHB3emxjeW9jamdleG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzI4NzcsImV4cCI6MjA2Mzc0ODg3N30.uY1GwqN3vaWlCvjscaPNLPYsAyJxE24rv8WuuZqHikw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);